# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

# Understanding suicidal ideation disparity between sexual minority and heterosexual Chinese young men: a multiple mediation model of social support sources, self-esteem, and depressive symptoms
- id: doi:10.3389/fpsyt.2024.1265722
  image: 
  buttons:
    - type: data
    - link: https://www.frontiersin.org/articles/10.3389/fpsyt.2024.1265722/full#supplementary-material
  tags:
    - public health
    - suicide interventions

# Dissociable memory modulation mechanisms facilitate fear amnesia at different timescales
- id: doi:10.1101/2024.04.16.589786
  image: 
  buttons:
    - type: source
      text: OSF
      link: https://osf.io/9agvk/
  tags:
    - memory reconsolidation
    - maladaptive memory
    - clinical treatment

# COVID-19 related stress during and one year after the first wave of the pandemic outbreak in China: The role of social support and perceptions of the pandemic
- id: doi:10.3389/fpsyt.2022.1009810
  image: 
  buttons:
    - type: data
    - link: https://www.frontiersin.org/journals/psychiatry/articles/10.3389/fpsyt.2022.1009810/full#supplementary-material
  tags:
    - public health
    - COVID-19

# COVID-19 Related Stress and Mental Health Outcomes 1 Year After the Peak of the Pandemic Outbreak in China: the Mediating Effect of Resilience and Social Support
- id: doi:10.3389/fpsyt.2022.828379
  image: 
  buttons:
    - type: source
      text: OSF
      link: https://osf.io/5z36p/
  tags:
    - public health
    - COVID-19

# Active suppression prevents the return of threat memory in humans
- id: doi:10.1038/s42003-021-02120-2 
  image: 
  buttons:
    - type: source
      text: OSF
      link: https://osf.io/qvt6r/
  tags: 
    - aversive memory
    - memory modulation

# Delay discounting decisions are linked to temporal distance representations of world events across cultures
- id: doi:10.1038/s41598-020-69700-w
  image: 
  buttons:
    - type: source
      text: OSF
      link: https://osf.io/kaqe9/
  tags:
    - delay discounting
    - reward valuation
    - cross-cultural study

# A Cross-Cultural Examination of the Role of Time Representation in Economic Decision-Making
- id: doi:10.1016/j.biopsych.2020.02.357
  image: 
  tags:
    - subjective time representation
    - decision-making
    - cross-cultural study

# Disparity in depressive symptoms between heterosexual and sexual minority men in China: The role of social support
- id: doi:10.1371/journal.pone.0226178
  image:
  buttons:
    - type: data
    - link: https://doi.org/10.1371/journal.pone.0226178.s001
  tags:
    - public health
    - sexual minorities
    - depressive symptoms

# Relationship between mental health and burden among primary caregivers of outpatients with schizophrenia
- id: doi:10.1111/famp.12340
  image:
  tags:
    - caregiver burden
    - mental health

# Neural computations of threat in the aftermath of combat trauma
- id: doi:10.1038/s41593-018-0315-x
  image: 
  buttons:
    - type: source
      text: OSF
      link: https://osf.io/rxsw2/
  tags:
    - PTSD
    - associative threat learning
    - neural computation

# Post-retrieval oxytocin facilitates next day extinction of threat memory in humans
- id: doi:10.1007/s00213-018-5074-6
  image: 
  tags:
    - memory reconsolidation
    - anxiety disorders
    - pharmacological treatment

# Reminder duration determines threat memory modification in humans
- id: doi:10.1038/s41598-018-27252-0
  image: 
  tags: 
    - memory reconsolidation
    - reminder duration effects
